pluginVer=1.13.6.0
crypticlibVer=26.8.2
paperApiVer=1.21.5-R0.1-SNAPSHOT
craftEngineVer=26.7.4
ecoEnchantsVer=12.5.1
ecoItemsVer=5.59.0
ecoVer=6.74.2
libreforgeVer=4.71.6
scoreVer=5.24.10.5
itemsAdderApiVer=3.6.3-beta-14
mmoItemsApiVer=6.9.5-SNAPSHOT
customFishingVer=2.3.24
jetbrainsAnnotationsVer=24.0.1
luckPermsApiVer=5.4
placeholderApiVer=2.11.6
adventureApiVer=4.14.0
emakiItemApiVer=2.7.0
emakiCoreLibApiVer=4.7.0
mythicLibDistVer=1.6.2-SNAPSHOT
mythicDistVer=5.3.5
neigeItemsVer=1.15.113
nexoVer=0.7.0
oraxenVer=1.191.0
packeteventsSpigotVer=2.12.2
playerpointsVer=3.2.5
protocolLibVer=5.4.0
sxItemVer=4.4.0
vaultApiVer=1.7
vaultUnlockedApiVer=2.16
advancedEnchantmentsApiVer=8.7.4
org.gradle.java.installations.paths=.jdks/jdk-25
