rootProject.name = "Craftorithm"
include("core")
include(
    "hook:azureflow",
    "hook:craftengine",
    "hook:ecoitems",
    "hook:executableitems",
    "hook:itemsadder",
    "hook:mmoitems",
    "hook:mythicmobs",
    "hook:neigeitems",
    "hook:nexo",
    "hook:oraxen",
    "hook:sx-item",
    "hook:packetevents",
    "hook:protocollib",
    "hook:vault",
    "hook:playerpoints"
)
include(
    "nms:v26_1",
    "nms:v1_21_7"
)