rootProject.name = "Craftorithm"

include("core")
include(
    "hook:azureflow",
    "hook:craftengine",
    "hook:ecoitems",
    "hook:executableitems",
    "hook:itemsadder",
    "hook:mmoitems",
    "hook:mythicmobs",
    "hook:neigeitems",
    "hook:nexo",
    "hook:oraxen",
    "hook:sx-item",
    "hook:packetevents",
    "hook:protocollib",
    "hook:vault",
    "hook:playerpoints"
)
include(
    "nms:v1_20",
    "nms:v1_20_2",
    "nms:v1_20_3",
    "nms:v1_20_5",
    "nms:v1_21",
    "nms:v1_21_3",
    "nms:v1_21_5",
    "nms:v1_21_7",
    "nms:v1_21_10_spigot",
    "nms:v1_21_10_paper",
    "nms:v1_21_11_spigot",
    "nms:v26_1_spigot",
    "nms:v26_1_paper",
)