name: Craftorithm
version: '${version}'
description: Craft recipes management system
main: com.github.yufiriamazenta.craftorithm.Craftorithm
api-version: '1.19'
load: POSTWORLD
softdepend: [ Vault, LuckPerms, PlayerPoints, PlaceholderAPI, ItemsAdder, Oraxen, MythicMobs, NeigeItems, MMOItems, EcoEnchants ]
authors: [ YufiriaMazenta ]
folia-supported: true
website: https://github.com/YufiriaMazenta/Craftorithm
permissions:
  craftorithm.command:
    description: Plugin command main permissions
  craftorithm.edit_recipe:
    default: op
