name: OasisRecipe
version: ${version}
main: top.oasismc.oasisrecipe.OasisRecipe
api-version: 1.13
load: STARTUP
softdepend: [ Vault, LuckPerms, PlayerPoints ]
authors: [ ChiyodaXiaoYi, StringStream_ ]
commands:
  oasisrecipe:
    aliases:
      - or
permissions:
  oasis.command.oasisrecipe:
    default: op